name:                blogpot
version:             0.1.0.0
github:              "arjaz/blogpot"
license:             BSD3
author:              "Eugene Rossokha"
maintainer:          "arjaz@protonmail.com"
copyright:           "2021 Eugene Rossokha"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/arjaz/blogpot#readme>

dependencies:
- base >= 4.7 && < 5
- text
- warp
- postgresql-simple
- uuid
- opaleye
- product-profunctors
- aeson
- servant
- servant-server
- polysemy
- polysemy-plugin
- servant-polysemy
- containers

library:
  source-dirs: src

ghc-options:
  - -fplugin=Polysemy.Plugin
  - -O2
  - -flate-specialise
  - -fspecialise-aggressively
  # Useful warnings
  - -Wall
  - -Wcompat
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

executables:
  blogpot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blogpot

tests:
  blogpot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blogpot
